### ISSUE TITLE
This is a first for me...

### ISSUE THREAD

**Issue by CamsShaft** [smallOS-cyberwarfare/smallOS-cyberwarfare#16]
Good evening! I'm trying to install this. I already have proot-distro installed and I'm getting an error saying this:

bash install_in_proot_distro.sh
rm: cannot remove '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/soscw': No such file or directory

Error: distribution 'soscw' is not installed.

[*] Installing soscw https://github.com/smallOS-cyberwarfare/smallOS-cyberwarfare...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/soscw'...
[!] The distribution download URL is not defined for CPU architecture 'aarch64'.
rm: cannot remove '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/soscw': No such file or directory
mv: cannot stat 'soscwfs': No such file or directory
System Ready:

$ soscw

I'm using a Samsung S22 Android 13 and when I used 'uname -m' it confirms it's aarch64 so I'm a little confused and hope its not something i did (it probably is). Thanks for any input!

EDIT: I also looked online and couldn't really find anything helpful other than reinstalling the OS which I would assume for this is termux which wouldn't be a big deal, but I would like to avoid reinstalling everything from scratch again. If so... c'est la vie 🤷‍♂️

**Comment by StringManolo** [comment]
There is no bug. Thats default behaviour. You should be able to run the distro by writting the command soscw.

Proot-distro added recently a bug where if you missing environment file in etc folder you can't start old distros.

I'm currently fixing it at the moment so everything works without aditional steps. You can manually fix it by running this command: touch ~/../usr/var/lib/proot-distro/installed-rootfs/soscw/etc/environment if you already have it installed. If not just try again, probably fixed when you reading this.
